### PR TITLE
Fixes for Julia nightly

### LINKED ISSUE #71: JLD now creates warnings, replace with JLD2
We are using JLD in the code, and it creates warnings because it is behaving improperly with FileIO - I think it's a type piracy problem. I tried to suppress the warnings by being more precise about what we were doing, but it wasn't possible. I think the long term solution is to move to the data pipeline and/or JLD2, but I'm open to other suggestions (and maybe this is fixed in `dev`?).

### PR DESCRIPTION
**Pull request by claireh93**
JLD is outdated, so dropping support for it and using JLD2 instead - Closes #71

### CODE REVIEW

**Comment by claireh93** [comment]
@richardreeve This should be sorted now - have tested it on the nightly release! Support for JuliaDB has been removed for now, pending their release of a new version.

File: src/ClimatePref/ClimatePref.jl [hunk 1]
```diff
@@ -9,27 +9,28 @@ function __init__()
     end
 end
 
+@warn "This functionality remains under development!"
```
Comment (richardreeve) [inline src/ClimatePref/ClimatePref.jl:12]: I think just delete all of these ClimatePref files...

**Review by richardreeve — CHANGES_REQUESTED** [review]
I think delete all of the ClimatePref files and then it'll be good to go.

**Review by richardreeve — APPROVED** [review]
